---
- name: Setting up the cluster on nodes
  hosts: [nodes]
  become: True
  roles:
     - role: node

- name: Setup OpenvSwitch on nodes
  hosts: [nodes]
  become: True
  tasks:
    - name: Import OpenvSwitch tasks
      import_tasks: setup_gre_tunnel_on_node.yml

