---
- name: Install OpenvSwitch
  yum:
    name: https://repos.fedorapeople.org/repos/openstack/EOL/openstack-juno/epel-7/openvswitch-2.3.1-2.el7.x86_64.rpm
    state: present
    update_cache: True

- name: Install Packages
  yum:
    name: ['epel-release', 'centos-release-openstack-train', 'bridge-utils', 'openvswitch', 'libibverbs', 'docker']
    state: present
    update_cache: True

- name: Make sure docker service is running
  ansible.builtin.systemd:
    state: started
    name: docker

- name: Make sure openvswitch service is running
  ansible.builtin.systemd:
    state: started
    name: openvswitch

- name: Generate docker configuration file
  template:
    src: docker.conf.j2
    dest: /etc/sysconfig/docker
  notify:
     - Restart docker

- name: Restarting docker to pick network changes
  ansible.builtin.systemd:
    name: docker
    state: restarted

- name: Add Routes on hosts
  command: ip route add {{ cluster_subnet }} dev docker0

- name: Setup openvswitch network on host
  command: "{{ item }}"
  with_items:
  - ovs-vsctl add-br br-int
  - ip link add veth0 type veth peer name veth1
  - ovs-vsctl add-port br-int veth1
  - brctl addif docker0 veth0
  - ip link set veth1 up
  - ip link set veth0 up
