name: Container Orchestration Service

on:
  push:
    branches:
      - '*'

  pull_request:
    branches: [ master,main ]


jobs:

  PrepareVersion:
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    steps:
    
    - name: checkout
      uses: actions/checkout@v2

    - name: version
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      uses: docker://ganeshdinesh/semrelgenerator:latest

    - name: Upload Version
      uses: actions/upload-artifact@v2
      with:
        name: version
        path: version_

  build:
    if: github.event_name != 'pull_request'
    needs: [PrepareVersion]
    runs-on: ubuntu-latest
    steps:
      
    - name: Checkout
      uses: actions/checkout@v2

    - name: Download Version
      uses: actions/download-artifact@v2
      with:
        name: version

    - name: Build The Dockerfile
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: ./src/
        file: ./src/Dockerfile
        push: false
        tags: ganeshdinesh/containerservice:latest

    - name: Tag The docker image
      shell: bash
      run: |
        Version=`cat version_`
        echo The Version is $Version
        docker tag ${{ steps.docker_build.outputs.digest }} ganeshdinesh/containerservice:$Version

